串口协议
Timyerc/development pull request #11
Opened 2024-11-18 03:10 UTC by zlq91

2024-12-07 07:35 UTC, tsunyi requested changes

2024-12-07 07:35 UTC, tsunyi commented on docs/Protocol/串口MSP协议.md
> +| preamble | 包的序言 | 总是为 0xFF |
包头

2024-12-07 07:35 UTC, tsunyi commented on docs/Protocol/串口MSP协议.md
> +| option | 包的选择 | 见下文 |
选项更准确些

2024-12-07 07:35 UTC, tsunyi commented on docs/Protocol/串口MSP协议.md
> +| 0x03 | DCODE_SOLAR_CLEANBOT |
其他设备补充

2024-12-07 07:35 UTC, tsunyi commented on docs/Protocol/串口MSP协议.md
> +| 226 | MSP_SET_GYRO_THRESHOLD | 设置陀螺仪阈值 |
指令按设备分，统一使用10进制

2024-12-07 10:37 UTC, zlq91 commented on docs/Protocol/串口MSP协议.md
> +| preamble | 包的序言 | 总是为 0xFF |
已改

2024-12-07 10:37 UTC, zlq91 commented on docs/Protocol/串口MSP协议.md
> +| option | 包的选择 | 见下文 |
已改

2024-12-07 10:38 UTC, zlq91 commented on docs/Protocol/串口MSP协议.md
> +| 226 | MSP_SET_GYRO_THRESHOLD | 设置陀螺仪阈值 |
已改

2024-12-07 10:48 UTC, zlq91 commented on docs/Protocol/串口MSP协议.md
> +| 0x03 | DCODE_SOLAR_CLEANBOT |
暂时不用，0X02是我看错了

2025-02-15 06:27 UTC, tsunyi approved these changes

2025-02-15 06:33 UTC, merged